INSERT INTO HELP_TOPIC (id, name) VALUES (8881, 'Getting Started');
INSERT INTO HELP_TOPIC (id, name) VALUES (8882, 'Application Usage');
INSERT INTO HELP_TOPIC (id, name) VALUES (8883, 'Features');
INSERT INTO HELP_TOPIC (id, name) VALUES (8884, 'About');

INSERT INTO HELP_ITEM (HELP_TOPIC_ID, TITLE, CONTENT) VALUES (8881, 'Item 1 of GS Topic', '<p><img src="http://ico.ooopic.com/ajax/iconpng/?id=165610.png" />This is a text.</p>');
INSERT INTO HELP_ITEM (HELP_TOPIC_ID, TITLE, CONTENT) VALUES (8881, 'Item 2 of GS Topic', 'Hello World');
INSERT INTO HELP_ITEM (HELP_TOPIC_ID, TITLE, CONTENT) VALUES (8881, 'Item 3 of GS Topic', 'Hello World');
INSERT INTO HELP_ITEM (HELP_TOPIC_ID, TITLE, CONTENT) VALUES (8881, 'Item 4 of GS Topic', 'Hello World');
INSERT INTO HELP_ITEM (HELP_TOPIC_ID, TITLE, CONTENT) VALUES (8881, 'Item 5 of GS Topic', 'Hello World');


INSERT INTO HELP_ITEM (HELP_TOPIC_ID, TITLE, CONTENT) VALUES (8882, 'Item 1 of AU Topic', 'Hello World');
INSERT INTO HELP_ITEM (HELP_TOPIC_ID, TITLE, CONTENT) VALUES (8882, 'Item 2 of AU Topic', 'Hello World');
INSERT INTO HELP_ITEM (HELP_TOPIC_ID, TITLE, CONTENT) VALUES (8882, 'Item 3 of AU Topic', 'Hello World');
INSERT INTO HELP_ITEM (HELP_TOPIC_ID, TITLE, CONTENT) VALUES (8882, 'Item 4 of AU Topic', 'Hello World');
INSERT INTO HELP_ITEM (HELP_TOPIC_ID, TITLE, CONTENT) VALUES (8882, 'Item 5 of AU Topic', 'Hello World');
INSERT INTO HELP_ITEM (HELP_TOPIC_ID, TITLE, CONTENT) VALUES (8882, 'Item 6 of AU Topic', 'Hello World');
INSERT INTO HELP_ITEM (HELP_TOPIC_ID, TITLE, CONTENT) VALUES (8882, 'Item 7 of AU Topic', 'Hello World');
INSERT INTO HELP_ITEM (HELP_TOPIC_ID, TITLE, CONTENT) VALUES (8882, 'Item 8 of AU Topic', 'Hello World');
INSERT INTO HELP_ITEM (HELP_TOPIC_ID, TITLE, CONTENT) VALUES (8882, 'Item 9 of AU Topic', 'Hello World');
INSERT INTO HELP_ITEM (HELP_TOPIC_ID, TITLE, CONTENT) VALUES (8882, 'Item 10 of AU Topic', 'Hello World');
INSERT INTO HELP_ITEM (HELP_TOPIC_ID, TITLE, CONTENT) VALUES (8882, 'Item 11 of AU Topic', 'Hello World');
INSERT INTO HELP_ITEM (HELP_TOPIC_ID, TITLE, CONTENT) VALUES (8882, 'Item 12 of AU Topic', 'Hello World');
INSERT INTO HELP_ITEM (HELP_TOPIC_ID, TITLE, CONTENT) VALUES (8882, 'Item 13 of AU Topic', 'Hello World');
INSERT INTO HELP_ITEM (HELP_TOPIC_ID, TITLE, CONTENT) VALUES (8882, 'Item 14 of AU Topic', 'Hello World');
INSERT INTO HELP_ITEM (HELP_TOPIC_ID, TITLE, CONTENT) VALUES (8882, 'Item 15 of AU Topic', 'Hello World');
INSERT INTO HELP_ITEM (HELP_TOPIC_ID, TITLE, CONTENT) VALUES (8882, 'Item 16 of AU Topic', 'Hello World');
INSERT INTO HELP_ITEM (HELP_TOPIC_ID, TITLE, CONTENT) VALUES (8882, 'Item 17 of AU Topic', 'Hello World');
INSERT INTO HELP_ITEM (HELP_TOPIC_ID, TITLE, CONTENT) VALUES (8882, 'Item 18 of AU Topic', 'Hello World');
INSERT INTO HELP_ITEM (HELP_TOPIC_ID, TITLE, CONTENT) VALUES (8882, 'Item 19 of AU Topic', 'Hello World');
INSERT INTO HELP_ITEM (HELP_TOPIC_ID, TITLE, CONTENT) VALUES (8882, 'Item 20 of AU Topic', 'Hello World');
INSERT INTO HELP_ITEM (HELP_TOPIC_ID, TITLE, CONTENT) VALUES (8882, 'Item 21 of AU Topic', 'Hello World');
INSERT INTO HELP_ITEM (HELP_TOPIC_ID, TITLE, CONTENT) VALUES (8882, 'Item 22 of AU Topic', 'Hello World');
INSERT INTO HELP_ITEM (HELP_TOPIC_ID, TITLE, CONTENT) VALUES (8882, 'Item 23 of AU Topic', 'Hello World');
INSERT INTO HELP_ITEM (HELP_TOPIC_ID, TITLE, CONTENT) VALUES (8882, 'Item 24 of AU Topic', 'Hello World');
INSERT INTO HELP_ITEM (HELP_TOPIC_ID, TITLE, CONTENT) VALUES (8882, 'Item 25 of AU Topic', 'Hello World');
INSERT INTO HELP_ITEM (HELP_TOPIC_ID, TITLE, CONTENT) VALUES (8882, 'Item 26 of AU Topic', 'Hello World');
INSERT INTO HELP_ITEM (HELP_TOPIC_ID, TITLE, CONTENT) VALUES (8882, 'Item 27 of AU Topic', 'Hello World');
INSERT INTO HELP_ITEM (HELP_TOPIC_ID, TITLE, CONTENT) VALUES (8882, 'Item 28 of AU Topic', 'Hello World');
INSERT INTO HELP_ITEM (HELP_TOPIC_ID, TITLE, CONTENT) VALUES (8882, 'Item 29 of AU Topic', 'Hello World');
INSERT INTO HELP_ITEM (HELP_TOPIC_ID, TITLE, CONTENT) VALUES (8882, 'Item 30 of AU Topic', 'Hello World');


INSERT INTO HELP_ITEM (HELP_TOPIC_ID, TITLE, CONTENT) VALUES (8883, 'Item 1 of Features Topic', 'Hello World');
INSERT INTO HELP_ITEM (HELP_TOPIC_ID, TITLE, CONTENT) VALUES (8883, 'Item 2 of Features Topic', 'Hello World');
INSERT INTO HELP_ITEM (HELP_TOPIC_ID, TITLE, CONTENT) VALUES (8883, 'Item 3 of Features Topic', 'Hello World');

INSERT INTO HELP_ITEM (HELP_TOPIC_ID, TITLE, CONTENT) VALUES (8884, 'Item 1 of About Topic', '');
INSERT INTO HELP_ITEM (HELP_TOPIC_ID, TITLE, CONTENT) VALUES (8884, 'Item 2 of About Topic', 'Hello World');
INSERT INTO HELP_ITEM (HELP_TOPIC_ID, TITLE, CONTENT) VALUES (8884, 'Item 3 of About Topic', 'Hello World');




